arp:
    #Publish all joint states 
    gazebo/joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50 

    #Effort Controllers
#    front_left_effort_controller:
#        type: effort_controllers/JointEffortController
#        joint: front_left_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}
#    front_right_effort_controller:
#        type: effort_controllers/JointEffortController
#        joint: front_right_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}
#    back_left_effort_controller:
#        type: effort_controllers/JointEffortController
#        joint: back_left_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}
#    back_right_effort_controller:
#        type: effort_controllers/JointEffortController
#        joint: back_right_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}

    #Velocity Controllers
#    front_left_velocity_controller:
#        type: effort_controllers/JointVelocityController
#        joint: front_left_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}
#    front_right_velocity_controller:
#        type: effort_controllers/JointVelocityController
#        joint: front_right_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}
#    back_left_velocity_controller:
#        type: effort_controllers/JointVelocityController
#        joint: back_left_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}
#    back_right_velocity_controller:
#        type: effort_controllers/JointVelocityController
#        joint: back_right_wheel_hinge
#        pid: {p: 100.0, i: 0.1, d: 10.0}

    #Velocity Controllers
    gazebo/front_left_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: front_left_wheel_hinge
        pid: {p: 100.0, i: 0.1, d: 10.0}
    gazebo/front_right_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: front_right_wheel_hinge
        pid: {p: 100.0, i: 0.1, d: 10.0}
    gazebo/back_left_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: back_left_wheel_hinge
        pid: {p: 100.0, i: 0.1, d: 10.0}
    gazebo/back_right_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: back_right_wheel_hinge
        pid: {p: 100.0, i: 0.1, d: 10.0}
         
