/**
Software License Agreement (BSD)

\file      controller.cpp
\authors   Mike Purvis <mpurvis@clearpathrobotics.com>
           Mike Irvine <mirvine@clearpathrobotics.com>
\copyright Copyright (c) 2013, Clearpath Robotics, Inc., All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the
following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this
list of conditions and the following
   disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following
   disclaimer in the documentation and/or other materials provided with the
distribution.
 * Neither the name of Clearpath Robotics nor the names of its contributors may
be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#include "arp_base/roboteq_driver/controller.h"
#include "arp_base/roboteq_driver/channel.h"

#include "serial/serial.h"

#include <boost/bind.hpp>
#include <boost/algorithm/string/replace.hpp>
#include <boost/algorithm/string/trim.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string/classification.hpp>
#include <unistd.h>
#include <iostream>
#include <sstream>

// Link to generated source from Microbasic script file.
extern const char* script_lines[];
extern const int script_ver = 0;

namespace roboteq
{

const std::string eol("\r");
const size_t max_line_length(128);

Controller::Controller()
    : port_("/dev/ttyUSB0"), baud_(115200), connected_(false),
      receiving_script_messages_(false), version_(""),
      start_script_attempts_(0), serial_(NULL), command("!", this),
      query("?", this), param("^", this)
{
}

/*
 * Inicializa as variaveis de conexão para o controlador
*/
void Controller::controlerInit(const char* port, int baud, std::string name)
{
  port_ = port;
  baud_ = baud;
  name_ = name;
}

/*
 * Adiciona um novo canal no controlador
*/
void Controller::addChannel(Channel* channel) { channels_.push_back(channel); }

/*
 * Conecta com a porta serial, fazendo cinco tentativas, caso obtenha sucesso sinaliza e sai do loop,
 * caso contrario retorna erro
*/
void Controller::connect()
{
  if (!serial_)
    serial_ = new serial::Serial();
  serial::Timeout to(serial::Timeout::simpleTimeout(500));
  serial_->setTimeout(to);
  serial_->setPort(port_);
  serial_->setBaudrate(baud_);

  for (int tries = 0; tries < 5; tries++)
  {
    try
    {
      serial_->open();
      query << "FID" << send;
      setSerialEcho(false);
      flush();
    }
    catch (serial::IOException)
    {
    }

    if (serial_->isOpen())
    {
      connected_ = true;
      return;
    }
    else
    {
      connected_ = false;
      ROS_INFO("Bad Connection with serial port Error %s", port_);
    }
  }

  ROS_INFO("Motor controller not responding.");
}

/*
 * Rotina de leitura da serial
 * subdividida em tres parte, a primeira responsavel por sinalizar para o ROS
 * quando o controlador recebeu os dados através de um ack,
 * a segunda responsavel por tratar os dados gerados pelo script
 * a terceira verifica a integridade do script, caso nao sinalize integridade
 * faz download do script contido no diretorio mbs
*/
void Controller::read()
{
  ROS_DEBUG_STREAM_NAMED("serial", "Bytes waiting: " << serial_->available());
  std::string msg = serial_->readline(max_line_length, eol);

  if (!msg.empty())
  {
    ROS_DEBUG_STREAM_NAMED("serial", "RX: " << msg);
    if (msg[0] == '+' || msg[0] == '-')
    {
      // Notify the ROS thread that a message response (ack/nack) has arrived.
      boost::lock_guard<boost::mutex> lock(last_response_mutex_);
      last_response_ = msg;
      last_response_available_.notify_one();
    }
    else if (msg[0] == '&')
    {
      receiving_script_messages_ = true;
      // Message generated by the Microbasic script.
      boost::trim(msg);
      if (msg[1] == 's')
      {
        processStatus(msg);
      }
      else if (msg[1] == 'f')
      {
        processFeedback(msg);
      }
    }
    else
    {
      // Unknown other message.
      ROS_WARN_STREAM("Unknown serial message received: " << msg);
    }
  }
  else
  {
    ROS_WARN_NAMED("serial", "Serial::readline() returned no data.");
    if (!receiving_script_messages_)
    {
      if (start_script_attempts_ < 5)
      {
        start_script_attempts_++;
        ROS_DEBUG("Attempt #%d to start MBS program.", start_script_attempts_);
        startScript();
        flush();
      }
      else
      {
        ROS_DEBUG("Attempting to download MBS program.");
        if (downloadScript())
        {
          start_script_attempts_ = 0;
        }
        ros::Duration(1.0).sleep();
      }
    }
    else
    {
      ROS_DEBUG("Script is believed to be in-place and running, so taking no "
                "action.");
    }
  }
}

/*
 * escreve os dados na seria
*/
void Controller::write(std::string msg) { tx_buffer_ << msg << eol; }

void Controller::flush()
{
  ROS_DEBUG_STREAM_NAMED("serial", "TX: " << boost::algorithm::replace_all_copy(
                                       tx_buffer_.str(), "\r", "\\r"));
  ssize_t bytes_written = serial_->write(tx_buffer_.str());
  if (bytes_written < tx_buffer_.tellp())
  {
    ROS_WARN_STREAM("Serial write timeout, " << bytes_written
                                             << " bytes written of "
                                             << tx_buffer_.tellp() << ".");
  }
  tx_buffer_.str("");
}

/*
 * verifica a integridade das mesnsagens de status e interpreta os valores recebidos
 * linkando com as variaveis pertinentes no precesso
*/
void Controller::processStatus(std::string str)
{
  std::vector<std::string> fields;
  boost::split(fields, str, boost::algorithm::is_any_of(":"));
  try
  {
    int reported_script_ver = boost::lexical_cast<int>(fields[1]);
    static int wrong_script_version_count = 0;
    if (reported_script_ver == script_ver)
    {
      wrong_script_version_count = 0;
    }
    else
    {
      if (++wrong_script_version_count > 5)
      {
        ROS_WARN_STREAM("Script version mismatch. Expecting "
                        << script_ver << " but controller consistently reports "
                        << reported_script_ver << ". "
                        << ". Now attempting download.");
        downloadScript();
      }
      return;
    }

    if (fields.size() != 7)
    {
      ROS_WARN("Wrong number of status fields. Dropping message.");
      return;
    }

    msg_.fault = boost::lexical_cast<int>(fields[2]);
    msg_.status = boost::lexical_cast<int>(fields[3]);
    msg_.internal_voltage = boost::lexical_cast<int>(fields[4]);
    msg_.adc_voltage = boost::lexical_cast<int>(fields[5]);
    msg_.ic_temperature = boost::lexical_cast<int>(fields[6]);
  }
  catch (std::bad_cast& e)
  {
    ROS_WARN("Failure parsing status data. Dropping message.");
    return;
  }
}

/*
 * verifica a integridade das mesnagen de feedback e verifica de qual motor foram recebidas
 * caso integras a mensagem é enviada para o channel corespondente ao motor para tratamento
 * das informações recebidas
*/
void Controller::processFeedback(std::string msg)
{
  std::vector<std::string> fields;
  boost::split(fields, msg, boost::algorithm::is_any_of(":"));
  if (fields.size() != 12)
  {
    ROS_WARN("Wrong number of feedback fields. Dropping message.");
    return;
  }
  int channel_num;
  try
  {
    channel_num = boost::lexical_cast<int>(fields[1]);
  }
  catch (std::bad_cast& e)
  {
    ROS_WARN("Failure parsing feedback channel number. Dropping message.");
    return;
  }
  if (channel_num >= 1 && channel_num <= channels_.size())
  {
    channels_[channel_num - 1]->feedbackCallback(fields);
  }
  else
  {
    ROS_WARN("Bad channel number. Dropping message.");
    return;
  }
}

/*
 * caso a versão do escript não esteja de acordo com a versão do software
 * é inicializado o download.
*/
bool Controller::downloadScript()
{
  ROS_DEBUG("Commanding driver to stop executing script.");

  // Stop the running script, flag us to start it up again after..
  stopScript();
  flush();
  receiving_script_messages_ = false;

  // Clear serial buffer to avoid any confusion.
  ros::Duration(0.5).sleep();
  serial_->read();

  // Send SLD.
  ROS_DEBUG("Commanding driver to enter download mode.");
  write("%SLD 321654987");
  flush();

  // Look for special ack from SLD.
  for (int find_ack = 0; find_ack < 7; find_ack++)
  {
    std::string msg = serial_->readline(max_line_length, eol);
    ROS_DEBUG_STREAM_NAMED("serial", "HLD-RX: " << msg);
    if (msg == "HLD\r")
      goto found_ack;
  }
  ROS_DEBUG("Could not enter download mode.");
  return false;
found_ack:

  // Send hex program, line by line, checking for an ack from each line.
  int line_num = 0;
  while (script_lines[line_num])
  {
    std::string line(script_lines[line_num]);
    write(line);
    flush();
    std::string ack = serial_->readline(max_line_length, eol);
    ROS_DEBUG_STREAM_NAMED("serial", "ACK-RX: " << ack);
    if (ack != "+\r")
      return false;
    line_num++;
  }
  return true;
}

} // namespace roboteq
